name: PR
'on':
  pull_request:
  workflow_dispatch: null
jobs:
  apple-darwin-x86_64-x86_64:
    runs-on: macos-11
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - run: /usr/local/bin/bazel version
